version: 2
jobs:
  deploy_main:
    docker:
      - image: circleci/node:16.9.1
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: npm install
          command: npm i
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build project
          command: npm run build
      - run:
          name: Deploy firebase Hosting
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_main:
          filters:
            branches:
              only: master
